services:
  - type: web
    name: fish-disease-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TRANSFORMERS_CACHE
        value: /opt/render/.cache/huggingface
    healthCheckPath: /health
